/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sapanatravel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Posakya
 */
public class SapanaTravel extends javax.swing.JFrame {
    Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form SapanaTravel
     */
    public SapanaTravel() {
        initComponents();       
        conn=JavaConnect.connector1();
        Update_table();
        Update_table1();
        Update_table2();
        CurrentDate();
        CurrentTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_traveldetail = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_passenger = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_passenger1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_bus_number = new javax.swing.JTextField();
        txt_driver_number = new javax.swing.JTextField();
        txt_available_seat = new javax.swing.JTextField();
        txt_destination = new javax.swing.JTextField();
        txt_bus_category = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jinsert = new javax.swing.JButton();
        jupdate = new javax.swing.JButton();
        jexit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jinsert1 = new javax.swing.JButton();
        jupdate1 = new javax.swing.JButton();
        jexit1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_pname = new javax.swing.JTextField();
        txt_seat = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        txt_destination1 = new javax.swing.JTextField();
        txt_busnumber = new javax.swing.JTextField();
        txt_buscategory = new javax.swing.JTextField();
        txt_date1 = new javax.swing.JTextField();
        txt_time = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_id1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jPanel2.setForeground(new java.awt.Color(255, 255, 0));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("         SAPANA    TRAVELS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        table_traveldetail.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        table_traveldetail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        table_traveldetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_traveldetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_traveldetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_traveldetail);
        if (table_traveldetail.getColumnModel().getColumnCount() > 0) {
            table_traveldetail.getColumnModel().getColumn(0).setResizable(false);
            table_traveldetail.getColumnModel().getColumn(0).setPreferredWidth(27);
            table_traveldetail.getColumnModel().getColumn(1).setResizable(false);
            table_traveldetail.getColumnModel().getColumn(1).setPreferredWidth(120);
            table_traveldetail.getColumnModel().getColumn(2).setResizable(false);
            table_traveldetail.getColumnModel().getColumn(2).setPreferredWidth(145);
            table_traveldetail.getColumnModel().getColumn(3).setResizable(false);
            table_traveldetail.getColumnModel().getColumn(3).setPreferredWidth(145);
            table_traveldetail.getColumnModel().getColumn(4).setResizable(false);
            table_traveldetail.getColumnModel().getColumn(4).setPreferredWidth(210);
            table_traveldetail.getColumnModel().getColumn(5).setResizable(false);
            table_traveldetail.getColumnModel().getColumn(5).setPreferredWidth(120);
            table_traveldetail.getColumnModel().getColumn(6).setResizable(false);
            table_traveldetail.getColumnModel().getColumn(6).setPreferredWidth(120);
        }

        jTabbedPane2.addTab("Travel Detail", jScrollPane1);

        table_passenger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_passenger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_passengerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_passenger);

        jTabbedPane2.addTab("A/C Detail", jScrollPane2);

        table_passenger1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_passenger1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_passenger1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_passenger1);

        jTabbedPane2.addTab("Non-A/C Detail", jScrollPane3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("  Bus Number");

        jLabel3.setDisplayedMnemonic('f');
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("  Driver Number");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("  Available Seat");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("  Destination");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("  Bus Category");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("  Date");

        txt_bus_number.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_driver_number.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_available_seat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_destination.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_bus_category.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_date.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("   Travel Detail");

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jinsert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jinsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/save.png"))); // NOI18N
        jinsert.setText("Insert");
        jinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertActionPerformed(evt);
            }
        });

        jupdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/update.png"))); // NOI18N
        jupdate.setText("Update");
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });

        jexit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/xit.png"))); // NOI18N
        jexit.setText("Exit");
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/delete.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/clear.png"))); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/print.png"))); // NOI18N
        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jupdate, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addComponent(jinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jexit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jexit)
                    .addComponent(jupdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(11, 11, 11))
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("  Id");

        txt_id.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_bus_number)
                            .addComponent(txt_driver_number)
                            .addComponent(txt_available_seat)
                            .addComponent(txt_destination)
                            .addComponent(txt_bus_category)
                            .addComponent(txt_date)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 140, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_id)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bus_number))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_driver_number, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_available_seat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_destination, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_bus_category, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        jTabbedPane1.addTab("Travel Detail", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setText("   Passenger Detail");

        jPanel7.setBackground(new java.awt.Color(51, 51, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jinsert1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jinsert1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/save.png"))); // NOI18N
        jinsert1.setText("Insert");
        jinsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsert1ActionPerformed(evt);
            }
        });

        jupdate1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jupdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/update.png"))); // NOI18N
        jupdate1.setText("Update");
        jupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdate1ActionPerformed(evt);
            }
        });

        jexit1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/xit.png"))); // NOI18N
        jexit1.setText("Exit");
        jexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexit1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/delete.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/clear.png"))); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapanatravel/print.png"))); // NOI18N
        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jupdate1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jinsert1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addComponent(jexit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jinsert1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jexit1)
                    .addComponent(jupdate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("  Passenger Name");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("  Seat Number");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("  Contact");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("  Destination");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("  Bus Number");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("  Bus Category");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("  Date");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("  Time");

        txt_pname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_seat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_contact.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_destination1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_destination1.setText("Birgunj to Kathmandu");

        txt_busnumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_buscategory.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_date1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_time.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("  Id");

        txt_id1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_id1.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_buscategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_busnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_destination1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_pname, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(txt_id1)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel17, jLabel18, jLabel19});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_buscategory, txt_busnumber, txt_contact, txt_date1, txt_destination1, txt_id1, txt_pname, txt_seat, txt_time});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_destination1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_busnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_buscategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_time))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel17, jLabel18, jLabel19});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_buscategory, txt_busnumber, txt_contact, txt_date1, txt_destination1, txt_id1, txt_pname, txt_seat, txt_time});

        jTabbedPane1.addTab("Passenger Detail", jPanel6);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setBounds(0, 0, 1000, 724);
    }// </editor-fold>//GEN-END:initComponents

    public void Update_table(){
         
       try{  String sql="select Id,Bus_No,Driver_No,Available_Seat,Destination,Bus_Category,Date  from travel_detail where Destination='Birgunj to Kathmandu'";
       
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_traveldetail.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    public void Update_table1(){
         
       try{  String sql="select Id,Passenger_Name,Seat_No,Phone,Destination,Bus_No,Bus_Category,Date,Time from passenger where Destination='Birgunj to Kathmandu' and Bus_Category='A/C'";
       
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_passenger.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    public void Update_table2(){
         
       try{  String sql="select Id,Passenger_Name,Seat_No,Phone,Destination,Bus_No,Bus_Category,Date,Time from passenger where Destination='Birgunj to Kathmandu' and Bus_Category='Non-A/C'";
       
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_passenger1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
      public void CurrentDate(){
         GregorianCalendar c=new GregorianCalendar();
        int day=c.get(Calendar.DAY_OF_MONTH);
        int month=c.get(Calendar.MONTH);
        int year=c.get(Calendar.YEAR);
        String date = +year+"-"+(month+1)+"-"+day;
        txt_date.setText(String.valueOf(date));
        txt_date1.setText(String.valueOf(date));
    }
public void CurrentTime(){
         GregorianCalendar c=new GregorianCalendar();
       int second=c.get(Calendar.SECOND);
       int hour=c.get(Calendar.HOUR_OF_DAY);
        int minute=c.get(Calendar.MINUTE);
        String time=+hour+":"+minute+":"+second;
        txt_time.setText(String.valueOf(time));
        //txt_time1.setText(String.valueOf(time));
    }
    private void jinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertActionPerformed
          try{
                String sql="insert into travel_detail values (?,?,?,?,?,?,?)";
                pst=conn.prepareStatement(sql);
               pst.setString(1,txt_id.getText());
                pst.setString(2,txt_bus_number.getText());
                 pst.setString(3,txt_driver_number.getText());
                  pst.setString(4,txt_available_seat.getText());
                   pst.setString(5,txt_destination.getText());
                    pst.setString(6,txt_bus_category.getText());
                     pst.setString(7,txt_date.getText());
                      pst.execute();
            JOptionPane.showMessageDialog(null,"Data Inserted");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
       }
        Update_table();
          
    }//GEN-LAST:event_jinsertActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
        String value1=txt_id.getText();
        String value2=txt_bus_number.getText();
        String value3=txt_driver_number.getText();
        String value4=txt_available_seat.getText();
        String value5=txt_destination.getText();
        String value6=txt_bus_category.getText();
        String value7=txt_date.getText();

        String sql="update travel_detail set Id='"+value1+"',Bus_No='"+value2+"',Driver_No='"+value3+"',Available_Seat='"+value4+"',Destination='"+value5+"',Bus_Category='"+value6+"',Date='"+value7+"' where Id='"+value1+"'";
        try{
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Updated");
 GregorianCalendar c=new GregorianCalendar();
                int day=c.get(Calendar.DAY_OF_MONTH);
                int month=c.get(Calendar.MONTH);
                int year=c.get(Calendar.YEAR);
                String date = +year+"-"+(month+1)+"-"+day;
                txt_date.setText(String.valueOf(date));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
         
          Update_table();
    }//GEN-LAST:event_jupdateActionPerformed

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jexitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int p = JOptionPane.showConfirmDialog(null,"Do you want to delete?","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0){
            String sql="delete from travel_detail where Id=?";
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_id.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Data Deleted");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
          Update_table();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         txt_id.setText("");
         txt_bus_number.setText("");
        txt_driver_number.setText("");
        txt_available_seat.setText("");
        txt_destination.setText("");
        txt_bus_category.setText("");
        txt_date.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MessageFormat Header=new MessageFormat("Report Print");
        MessageFormat Footer=new MessageFormat("Page {0,number,integer} ");
        try{
            table_traveldetail.print(JTable.PrintMode.NORMAL,Header,Footer);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot Print %s%n",e.getMessage());

        }       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void table_traveldetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_traveldetailMouseClicked
                     try{
           int row=table_traveldetail.getSelectedRow();
           String s=(table_traveldetail.getModel().getValueAt(row,0).toString());
           String sql="select Id,Bus_No,Driver_No,Available_Seat,Destination,Bus_Category,Date from travel_detail where Id='"+s+"'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           if(rs.next()){
               String add1=rs.getString("Id");
               txt_id.setText(add1);
               String add2=rs.getString("Bus_No");
               txt_bus_number.setText(add2);
               String add3=rs.getString("Driver_No");
               txt_driver_number.setText(add3);
             
               String add4=rs.getString("Available_Seat");
              txt_available_seat.setText(add4);
               String add5=rs.getString("Destination");
               txt_destination.setText(add5);
               String add6=rs.getString("Bus_Category");
               txt_bus_category.setText(add6);
                String add7=rs.getString("Date");
               txt_date.setText(add7);
              
            GregorianCalendar c=new GregorianCalendar();
                int day=c.get(Calendar.DAY_OF_MONTH);
                int month=c.get(Calendar.MONTH);
                int year=c.get(Calendar.YEAR);
                String date = +year+"-"+(month+1)+"-"+day;
                txt_date.setText(String.valueOf(date));
          
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
                       Update_table();
    }//GEN-LAST:event_table_traveldetailMouseClicked

    private void jinsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsert1ActionPerformed
         try{
                String sql="insert into passenger values (?,?,?,?,?,?,?,?,?)";
                pst=conn.prepareStatement(sql);
                 pst.setString(1,txt_id1.getText());
               pst.setString(2,txt_pname.getText());
                pst.setString(3,txt_seat.getText());
                 pst.setString(4,txt_contact.getText());
                  pst.setString(5,txt_destination1.getText());
                  pst.setString(6,txt_busnumber.getText());
                   pst.setString(7,txt_buscategory.getText());
                    pst.setString(8,txt_date1.getText());
                     pst.setString(9,txt_time.getText());
                      pst.execute();
            JOptionPane.showMessageDialog(null,"Data Inserted");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
       }
         Update_table1();
         Update_table2();
    }//GEN-LAST:event_jinsert1ActionPerformed

    private void jupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdate1ActionPerformed
        String value1=txt_id1.getText();
        String value2=txt_pname.getText();
        String value3=txt_seat.getText();
        String value4=txt_contact.getText();
        String value5=txt_destination1.getText();
        String value6=txt_busnumber.getText();
        String value7=txt_buscategory.getText();
        String value8=txt_date1.getText();
        String value9=txt_time.getText();

       // String sql="update travel_detail set Id='"+value1+"',Bus_No='"+value2+"',Driver_No='"+value3+"',Available_Seat='"+value4+"',Destination='"+value5+"',Bus_Category='"+value6+"',Date='"+value7+"' where Id='"+value1+"'";
 String sql="update passenger set Id='"+value1+"',Passenger_Name='"+value2+"',Seat_No='"+value3+"',Phone='"+value4+"',Destination='"+value5+"',Bus_No='"+value6+"',Bus_Category='"+value7+"',Date='"+value8+"',Time='"+value9+"' where Id='"+value1+"'";

        try{
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Updated");
 GregorianCalendar c=new GregorianCalendar();
                int day=c.get(Calendar.DAY_OF_MONTH);
                int month=c.get(Calendar.MONTH);
                int year=c.get(Calendar.YEAR);
                String date = +year+"-"+(month+1)+"-"+day;
                txt_date.setText(String.valueOf(date));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
          Update_table1();
          Update_table2();
    }//GEN-LAST:event_jupdate1ActionPerformed

    private void jexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexit1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jexit1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          int p = JOptionPane.showConfirmDialog(null,"Do you want to delete?","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0){
            String sql="delete from passenger where Id=?";
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_id1.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Data Deleted");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
         Update_table1();
         Update_table2();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       txt_id1.setText("");
        txt_pname.setText("");
       txt_seat.setText("");
       txt_contact.setText("");
       txt_destination1.setText("");
       txt_busnumber.setText("");
       txt_buscategory.setText("");
       txt_date1.setText("");
       txt_time.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         MessageFormat Header=new MessageFormat("Report Print");
        MessageFormat Footer=new MessageFormat("Page {0,number,integer} ");
        try{
            table_passenger.print(JTable.PrintMode.NORMAL,Header,Footer);
             table_passenger1.print(JTable.PrintMode.NORMAL,Header,Footer);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot Print %s%n",e.getMessage());

        }    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void table_passengerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_passengerMouseClicked
         try{
           int row=table_passenger.getSelectedRow();
           String s=(table_passenger.getModel().getValueAt(row,0).toString());
           String sql="select Id,Passenger_Name,Seat_No,Phone,Destination,Bus_No,Bus_Category,Date,Time from passenger where Id='"+s+"'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           if(rs.next()){
               String add1=rs.getString("Id");
               txt_id1.setText(add1);
               String add2=rs.getString("Passenger_Name");
               txt_pname.setText(add2);
               String add3=rs.getString("Seat_No");
               txt_seat.setText(add3);
               String add4=rs.getString("Phone");
               txt_contact.setText(add4);
               String add5=rs.getString("Destination");
              txt_destination1.setText(add5);
               String add6=rs.getString("Bus_No");
               txt_busnumber.setText(add6);
               String add7=rs.getString("Bus_Category");
               txt_buscategory.setText(add7);
                String add8=rs.getString("Date");
               txt_date1.setText(add8);
               String add9=rs.getString("Time");
               txt_time.setText(add9);
              
            GregorianCalendar c=new GregorianCalendar();
                int day=c.get(Calendar.DAY_OF_MONTH);
                int month=c.get(Calendar.MONTH);
                int year=c.get(Calendar.YEAR);
                String date = +year+"-"+(month+1)+"-"+day;
                txt_date1.setText(String.valueOf(date));
                int second=c.get(Calendar.SECOND);
                int hour=c.get(Calendar.HOUR_OF_DAY);
                int minute=c.get(Calendar.MINUTE);
                String time=+hour+":"+minute+":"+second;
                txt_time.setText(String.valueOf(time));
          
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
          Update_table1();
          Update_table2();
    }//GEN-LAST:event_table_passengerMouseClicked

    private void table_passenger1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_passenger1MouseClicked
       try{
           int row=table_passenger1.getSelectedRow();
           String s=(table_passenger1.getModel().getValueAt(row,0).toString());
           String sql="select Id,Passenger_Name,Seat_No,Phone,Destination,Bus_No,Bus_Category,Date,Time from passenger where Id='"+s+"'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           if(rs.next()){
               String add1=rs.getString("Id");
               txt_id1.setText(add1);
               String add2=rs.getString("Passenger_Name");
               txt_pname.setText(add2);
               String add3=rs.getString("Seat_No");
               txt_seat.setText(add3);
               String add4=rs.getString("Phone");
               txt_contact.setText(add4);
             
               String add5=rs.getString("Destination");
              txt_destination1.setText(add5);
               String add6=rs.getString("Bus_No");
               txt_busnumber.setText(add6);
               String add7=rs.getString("Bus_Category");
               txt_buscategory.setText(add7);
                String add8=rs.getString("Date");
               txt_date1.setText(add8);
               String add9=rs.getString("Time");
               txt_time.setText(add9);
              
            GregorianCalendar c=new GregorianCalendar();
                int day=c.get(Calendar.DAY_OF_MONTH);
                int month=c.get(Calendar.MONTH);
                int year=c.get(Calendar.YEAR);
                String date = +year+"-"+(month+1)+"-"+day;
                txt_date1.setText(String.valueOf(date));
                int second=c.get(Calendar.SECOND);
                int hour=c.get(Calendar.HOUR_OF_DAY);
                int minute=c.get(Calendar.MINUTE);
                String time=+hour+":"+minute+":"+second;
                txt_time.setText(String.valueOf(time));
          
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
       Update_table2();
    }//GEN-LAST:event_table_passenger1MouseClicked

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        Update_table2();
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SapanaTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SapanaTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SapanaTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SapanaTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SapanaTravel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jexit;
    private javax.swing.JButton jexit1;
    private javax.swing.JButton jinsert;
    private javax.swing.JButton jinsert1;
    private javax.swing.JButton jupdate;
    private javax.swing.JButton jupdate1;
    private javax.swing.JTable table_passenger;
    private javax.swing.JTable table_passenger1;
    private javax.swing.JTable table_traveldetail;
    private javax.swing.JTextField txt_available_seat;
    private javax.swing.JTextField txt_bus_category;
    private javax.swing.JTextField txt_bus_number;
    private javax.swing.JTextField txt_buscategory;
    private javax.swing.JTextField txt_busnumber;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_date1;
    private javax.swing.JTextField txt_destination;
    private javax.swing.JTextField txt_destination1;
    private javax.swing.JTextField txt_driver_number;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id1;
    private javax.swing.JTextField txt_pname;
    private javax.swing.JTextField txt_seat;
    private javax.swing.JTextField txt_time;
    // End of variables declaration//GEN-END:variables
}
